// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEqGRgVXaBO8KiitZIGEjieFGu_yA7AOs',
    appId: '1:685168261597:web:818bd27788afac31bfde34',
    messagingSenderId: '685168261597',
    projectId: 'e-commerce-32389',
    authDomain: 'e-commerce-32389.firebaseapp.com',
    databaseURL: 'https://e-commerce-32389.firebaseio.com',
    storageBucket: 'e-commerce-32389.appspot.com',
    measurementId: 'G-B5LWW57YJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0ubdA4NtdemSbiVsfDozYiZx5t7B4OJs',
    appId: '1:685168261597:android:997ce5cb9e541ba7bfde34',
    messagingSenderId: '685168261597',
    projectId: 'e-commerce-32389',
    databaseURL: 'https://e-commerce-32389.firebaseio.com',
    storageBucket: 'e-commerce-32389.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsa1OJWscrLzM1KaO6Z07EwjKlh-GaHGs',
    appId: '1:685168261597:ios:d6322b2188e8ce8bbfde34',
    messagingSenderId: '685168261597',
    projectId: 'e-commerce-32389',
    databaseURL: 'https://e-commerce-32389.firebaseio.com',
    storageBucket: 'e-commerce-32389.appspot.com',
    iosClientId: '685168261597-ci8cnbveg9m9lbli4pqjm311t6ipf1ae.apps.googleusercontent.com',
    iosBundleId: 'us.farrukh.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsa1OJWscrLzM1KaO6Z07EwjKlh-GaHGs',
    appId: '1:685168261597:ios:dcf96f99d5ccad1abfde34',
    messagingSenderId: '685168261597',
    projectId: 'e-commerce-32389',
    databaseURL: 'https://e-commerce-32389.firebaseio.com',
    storageBucket: 'e-commerce-32389.appspot.com',
    iosClientId: '685168261597-o69jjiugecteffajdrgiagifmgma44vv.apps.googleusercontent.com',
    iosBundleId: 'us.farrukh.ecommerce',
  );
}
